version: '3.8'
services:
  dev-db:
    image: postgres:13
    platform: linux/amd64
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    platform: linux/amd64
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
